//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSTOKPROJESİ.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class KATEGORI_TABLOSU
    {
        public KATEGORI_TABLOSU()
        {
            this.URUN_TABLOSU = new HashSet<URUN_TABLOSU>();
        }
    
        public short KATEGORIID { get; set; }

        [Required(ErrorMessage="Kategori adı boş geçilemez!")]
        public string KATEGORIAD { get; set; }
    
        public virtual ICollection<URUN_TABLOSU> URUN_TABLOSU { get; set; }
    }
}
