//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSTOKPROJESİ.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUN_TABLOSU
    {
        public URUN_TABLOSU()
        {
            this.SATIS_TABLOSU = new HashSet<SATIS_TABLOSU>();
        }
    
        public int URUNID { get; set; }
        public string URUNAD { get; set; }
        public Nullable<short> URUNKATEGORI { get; set; }
        public Nullable<decimal> URUNFIYAT { get; set; }
        public string URUNMARKA { get; set; }
        public Nullable<byte> URUNSTOK { get; set; }
    
        public virtual KATEGORI_TABLOSU KATEGORI_TABLOSU { get; set; }
        public virtual ICollection<SATIS_TABLOSU> SATIS_TABLOSU { get; set; }
    }
}
